### ISSUE TITLE
rpm.mritd.me  没有维护了么 

### ISSUE THREAD

**Issue by OSMeteor** [mritd/docker-library#4]
tee /etc/yum.repos.d/mritd.repo << EOF
[mritdrepo]
name=Mritd Repository
baseurl=https://rpm.mritd.me/centos/7/x86_64
enabled=1
gpgcheck=1
gpgkey=https://cdn.mritd.me/keys/rpm.public.key
EOF

**Comment by mritd** [comment]
@OSMeteor 请访问 https://yum.mritd.me 由于域名备案问题 cdn 绑定掉了
